cmd/caster/caster.go
cmd/forger/forger.go
cmd/smelter/smelt.go
cmd/smelter/split.go
cmd/utils/compiler.go
cmd/utils/compiler_test.go
cmd/utils/generator.go
cmd/utils/generator_test.go
cmd/utils/utils.go
cmd/utils/utils_test.go
go.mod
go.sum
integration-tests/prepare_and_cast_tool_test.go

The PR
- does major refactoring, breaking functions into smaller ones
- adds tests, including an integration test of sorts

major refactor, add tests

---

cmd/caster/caster.go
cmd/forger/forger.go
cmd/smelter/smelt.go
cmd/smelter/split.go
integration-tests/prepare_and_cast_tool_test.go

The PR fixes broken integration test and further breaks down casting. Now we can add test cases and chainsaw tests to validate inputs and outputs in the integration test.

fix integration test and further break down casting

---

input/config.yaml
input/kuberay-operator/values.yaml
input/psmdb-operator/psmdb-operator-values.yaml

Added the percona operator for mongodb

added psmdb operator

---

input/k8s-cluster-secret-store/README.md
input/k8s-cluster-secret-store/manifests.yaml
input/minio-tenant/README.md
input/minio-tenant/values.yaml

This PR is mainly for editing the value of refreshInterval not to refresh its secret every 30 mins.
Updating grafana-loki will follow based on this update.

Minio extra buckets

---

input/1password-cluster-secret-store/manifests.yaml
input/config-silogen-rnd.yaml
input/k8s-cluster-secret-store/manifests.yaml
input/minio-tenant/README.md
input/minio-tenant/values.yaml

oci2-deploy-minio
increase mimir size
increase minio size and update readme

1password secret store to rnd release

---

input/k8s-cluster-secret-store/manifests.yaml

fix-tab-in-manifest

---

input/otel-lgtm-stack/otel-lgtm-manifests.yaml

This PR adds PVCs to otel-lgtm-stack.
Only lgtm-stack with pvc tested without otel-collector agent.

add PVCs to lgtm-stack

---

input/config-silogen-core.yaml
input/config-silogen-rnd.yaml

longhorn is now in bash installs

remove longhorn

---

input/config.yaml
input/dummy-secret/README.md
input/dummy-secret/dummy-secret-monitoring-tools.yaml
input/grafana/grafana-values.yaml
input/k8s-cluster-secret-store/manifests.yaml
input/promtail/promtail-values.yaml

This PR removes a dummy secret of grafana by adding external-secrets.

delete dummy-secret and modify grafana and promtail to use external-secrets

---

input/kyverno/kyverno-policies.yaml

exclude-amd-gpu-operator-from-kyverno

---

input/otel-lgtm-stack/otel-lgtm-manifests.yaml

This will work. It's been tested on kind cluster on mac with "standard" storageclass.

add storageclass at lgtm-stack

---

setup-cluster/setup-forge.sh

Actually from creating the new oci clusters. Thinko in branch name

Updates to setup-forge

---

.github/workflows/release.yaml

something like this that we want?
not tested yet

Workflows delete release "deploy" if exists

---

input/grafana-loki/grafana-loki-values.yaml

A small fix for loki on RKE clusters by changing the value of storageClass name

small fix loki

---

input/config.yaml
input/grafana-dashboards/lgtm-gpu-metrics-dashboard.yaml
input/otel-lgtm-stack/dashboards/lgtm-default-dashboards.yaml
input/otel-lgtm-stack/dashboards/lgtm-gpu-metrics-dashboard.yaml
input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml

This PR updates scarpe_configs and dashboards for lgtm-stack.
Scraping job for gpu metrics is added.

update scrape_configs and dashboards for lgtm-stack

---

input/otel-lgtm-stack/otel-lgtm/modified-manifests.yaml

rollback to default

---

input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml

This PR adds two more scraping endpoints for otel-collector-metrics

add-additional-scrape-jobs-minio

---

input/1password-cluster-secret-store/manifests/ClusterSecretStore_onepass-oci.yaml
input/1password-cluster-secret-store/manifests/ExternalSecret_minio_example.yaml
input/1password-cluster-secret-store/manifests/ExternalSecret_test-1.yaml

This PR changes the name of the CSS to onepass

Delete oci suffix

---

input/grafana-loki/grafana-loki-values.yaml
input/grafana-mimir/grafana-mimir-values.yaml

This PR changes the s3 endpoints of Mimir and Loki to have http endpoint.

Change s3 endpoint from https to http

---

input/k8s-cluster-secret-store/manifests.yaml

add-realm-creds

---

input/config.yaml

need to also update input/config.yaml for yesterdays new input prometheus-app-config. 
This look ok?

Update config.yaml for prometheus-app-config

---

cmd/utils/imageutils.go

- Updated getQuaySHA() to handle manifest lists properly
- Added support for platform-specific manifest extraction
- Fixed issue where manifest list digest was returned instead of pullable platform digest
- Maintains backward compatibility with single manifests
- Resolves "image not found" errors when pulling quay.io images with SHA references

Fix quay.io image SHA resolution for multi-architecture images

---

input/airm-airm-config/airm-configure-rbac-cluster-role-binding.yaml
input/airm-airm-config/airm-configure-rbac-cluster-role.yaml
input/airm-airm-config/airm-configure-rbac-sa.yaml
input/airm-airm-config/airm-configure.yaml
input/config-updater/manifests/app-domain-updater.yaml

Domain updater image

---

input/airm-airm-config/airm-cluster.yaml

fix: issue 327 - remove backups in default forge setup

fix: issue 327 - remove backups in default forge setup

---

input/keycloak-airm-config/keycloak-cluster.yaml

fix: issue 327 - remove backups for CNPG Keycloak
Andy said Keycloak is going to be refactored soon, but this was a 1-minute fix 😄

fix: issue 327 - remove backups for CNPG Keycloak

---

input/airm-airm-config/airm.yaml
input/airm-configure/airm-configure-configmap-base.yaml
input/airm-configure/airm-configure-dispatcher-rbac.yaml

Please double check these images

V2025.08.001 release

---

input/airm-airm-config/airm.yaml
input/airm-configure/airm-configure-configmap-base.yaml
input/airm-configure/airm-configure-dispatcher-rbac.yaml
input/airm-configure/airm-configure.yaml

Add workload registration init-container to airm

---

input/keycloak-config/airm-realm-configmap.yaml
input/keycloak-config/keycloak.yaml
input/keycloak-config/secret-generator-configmap.yaml

feat(KC): add k8s client to realm export for airm

feat(KC): add k8s client to realm export for airm

---

input/airm/airm-full-stack.yaml

https://groups.google.com/g/quay-sig/c/OQ2y99cYxFo has been deprecated

Pin liquibase version to not use quay.io/lib
