silogen/cluster-forge

- cmd/smelter/split.go
- input/config.yaml
- input/dummy-secret/dummy-secret-monitoring-tools.yaml
- input/minio/README-minio.md
- input/minio/minio-values.yaml
This PR introduces Minio as a scaffold bucket provider for monitoring backend setup.
A `preclean` function in `split.go` addresses invisible tab characters(in the first picture as "^I") in the Minio configmap's "initialize" field create from helm.
Note: In the "working/minio" Job YAML, deleting (not commenting) annotations determines inclusion during the "cast" phase. README also is added inside of input/minio folder.
---
> add-minio: add minio and preclean function

- input/dummy-grafana-dashboard/README.md
- input/dummy-grafana-dashboard/dummy-grafana-dashboards.yaml
- input/dummy-secret/dummy-secret-monitoring-tools.yaml
- input/grafana/grafana-values.yaml
This PR makes the sidecar of grafana automatically detects and collects dashboard given by configmap having label "grafana_dashboard".
After getting through all processes(smelt, cast, and forge), please apply ConfigMap.yaml at input/dummy-grafana-dashboard/dummy-grafana-dashboards.yaml.
Adding this ConfigMap during the main process will come soon.
> Add grafana demo dashboards

- input/config.yaml
- input/dummy-secret/dummy-secret-monitoring-tools.yaml
- input/grafana-loki/grafana-loki-values.yaml
- input/promtail/dummy-secret-promtail.yaml
- input/promtail/promtail-values.yaml
This PR adds Grafana-Loki to cluster-forge.
Loki is a backend for collecting logs from Promtail and storing data to its dedicated bucket.
The endpoint of Promtail changed to the service of Loki.
`Warning!!`
Giving a bucket is requirement for Loki. To deploy minio as a bucket provider, annotations in "Job_minio-post-job.yaml" should be deleted after "smelting"
Minimum tools to check loki are:
- promtail
- dummy-secret
- minio
- loki
It is possible to check the dedicated bucket manually after deployment by commands as follows:
- kubectl port-forward -n minio svc/minio 9000:9000
- mc alias set cluster-forge-minio http://localhost:9000 externalSecret A123examplesecretpassword
- mc ls cluster-forge-minio/cluster-forge-loki-test-dummy/
> add-loki: add loki. edit promtial to point loki. edit the names of keys

- input/config.yaml
- input/external-secrets/k8s-provider-related.yaml
This PR adds "ClusterSecretStore" having k8s secret as a backend.
The nominal capability of k8s provider would be "ReadWrite". However, SA "external-secrets-readonly" attached to "ClusterSecretStore" has verbs such as "Get", "List", "Watch".
So only fetching the values of a secret in default namespace is possible.
> external-secrets-add-k8s-clustersecretstore: adding cluster_secret_store

- input/grafana/grafana-values.yaml
This PR enables anonymous access for grafana. 
Viewer role is given to anonymous users.
> update-grafana: enable anonymous access

- README.md
- input/config.yaml
- input/openobserve-collector/manifests.yaml
- input/openobserve/README.md
- input/openobserve/openobserve-standalone-values.yaml
For [issue 96](https://github.com/silogen/platform/issues/96).
This PR adds OpenObserve and required tools to cluster-forge. OpenObserve works as a backend giving much less footprints compared to deploying all Grafana-Mimir, Grafana-Loki, and Grafana-Tempo.
Included tools this PR are:
- OpenObserve
- OpenObserve-Collector (modified version of OpenTelemetry-Collector)
- OpenTelemetry-Operator
- Promttheus-CRDs
After deploying, OpenObserve is accessible by port-forwarding
```
kubectl --namespace openobserve port-forward svc/o2-openobserve-standalone 5080:5080
```
> Add openobserve, opentelemtry-operator, and openobserve-collector

- README.md
- input/config.yaml
- input/otel-lgtm-stack/README.md
- input/otel-lgtm-stack/otel-lgtm-manifests.yaml
This PR adds otel-lgtm-stack to cluster-forge.
Copied from README as follows:
```
- cert-manager
- opentelemetry-operator
- prometheus-crds
- otel-collector(agent)
- otel-lgtm
This otel-collector(agent) manifests are created from the modification of openobserve-collector manifests. 
Collector(agent) acting like node-exporter sends telemetries to the endpoint of otel-collector(gateway) which is a component of otel-lgtm stack. 
Current instrumentations are configured to send telemetries to the endpoint of otel-lgtm. 
Users/Developers who want to use auto instrumation need to implement by giving an annotation to their pods.
- https://github.com/grafana/docker-otel-lgtm/tree/main
kubectl port-forward -n otel-lgtm-stack service/lgtm-stack 3000:3000 4317:4317 4318:4318
id/password of grafana: …
```
> Add otel-lgtm-stack to cluster-forge

- input/config.yaml
- input/dummy-secret/dummy-secret-monitoring-tools.yaml
- input/grafana-mimir/grafana-mimir-values.yaml
- input/k8s-cluster-secret-store/manifests.yaml
The result of this PR is a part of replacing "dummy-secret" with external-secrets.
This PR makes "grafana-mimir" could work with "minio-tenant" and "external-secerts". 
(previously, it worked with insecure "minio-standard" with dummy-secrets)
"dummy-secret" will be completely removed after updating "promtail" and "grafana"
> edit mimir and delete a part of dummy-secret

- input/otel-lgtm-stack/otel-lgtm/modified-manifests.yaml
This PR adds requests and limits of resources to LGTM stack.
LGTM-stack was blocked on a cluster having kyverno policy.
It could be good that numbers of requests and limits updated later on based on actual usages.
> add resources.requests and resources.limits for lgtm stack

- .github/workflows/release.yaml
- setup-cluster/setup-forge.sh
This PR updates workflow to add ingress to release and add wait_for_namespaces function to setup-forge.sh script before applying ingress.yaml line. I guess that 300 seconds for checking the existence of each namespace will be enough based on my experience observing the argocd app so far.
The order will be...
- run `sudo sed -i "s/{{CONTROL_IP}}/$MAIN_IP/g" ingress/ingress.yaml`  inside if clause to use `$MAIN_IP`
- run `wait_for_namespaces function`
- run `KUBECONFIG==$HOME/.kube/config kubectl apply -f ingress/ingress.yaml` outside of if clause
> Update workflow to add ingress to release

- input/1password-cluster-secret-store/manifests/Namespace_1password-cluster-secret-store.yaml
This PR deletes a manifest in 1password-cluster-secret-store folder, which creates a "external-secret" namespace.
This gets rid of "out of sync" from the both "external-secret" and "1password-cluster-secret" tools trying to handle "external-secret" namespace.
From now on, "external-secret"(syncwave: -1) tool should be deployed together with "1password-cluster-secret-store"(syncwave: 0). Otherwise, it will fail to deploy "input/1password-cluster-secret-store/manifests/Service_central-onepass-connect.yaml"
> Delete a manifest creating external-secrets namespace

- input/otel-lgtm-stack/otel-lgtm/modified-manifests.yaml
This PR increases memory limi from 2Gi to 6Gi to prevent it from OOM.
A prometheus query created OOM.
> increase memory limit for lgtm stack

- input/otel-lgtm-stack/otel-lgtm/modified-manifests.yaml
This PR will solve an issue of deployment controlled by argocd app. Previously deployed lgtm pod holds PVC and PV so newly created lgtm pod cannot be up until old one disappears.
> Add recreate strategy to lgtm deployment

- input/config.yaml
- input/grafana-dashboards/lgtm-minio-dashboard.yaml
- input/otel-lgtm-stack/dashboards/lgtm-minio-dashboard.yaml
This PR adds a simple minio dashboard to lgtm-stack.
Minio-tenant in oci clusters exposes its metrics and otel-collector for metrics collects the metrics.
> Add minio-dashboard

- input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml
This PR updates the values of endpoints for otel-collector-metrics/logs to have their headscale proxy points.
After smelting to get "otel-lgtm-stack", the following two things have to be updated before applying otel-lgtm-stack manifests.
- Value of label "k8s_cluster_name"
- Value of header "X-Scope-OrgID" 
```
processors:
attributes:
actions:
- key: k8s_cluster_name
action: insert
value: "cluster-name" <--- here
headers:
"X-Scope-OrgID": "loki-tenant-cluster-name" <--- here
```
> Update endpoints of otel collectors

- input/config.yaml
This PR upgrades the version of Grafana Helm from "8.4.6(grafana version: 11.1.4)" to "8.12.0(grafana version: 11.6.0)".
The new version of Grafana was tested on a kind cluster
> Upgrade grafana helm version

- input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml
This PR adds "attributes process" adding "k8s_cluster_name"  label to all metrics.
Tested in ociops cluster.
> add attributes process to otel-collector-metric

- .github/workflows/release.yaml
renaming to 'clusterforge'. Makes it way easier for clusterbloom
> stop using release type as name for folder

- input/1password-cluster-secret-store/manifests/ExternalSecret_grafana-loki.yaml
- input/1password-cluster-secret-store/manifests/ExternalSecret_grafana-mimir.yaml
- input/1password-cluster-secret-store/manifests/ExternalSecret_grafana.yaml
This PR add three external-secrets for fetching secrets from 1password for monitoring tools in ociops.
After this PR, follow-up job will be updating monitoring tool side external-secrets to fetch from the secrets in cf-es-backend, not from "fake-cluster-secret-store"
> Add external-secrets calling secrets from 1password

- input/grafana-loki/grafana-loki-values.yaml
- input/grafana-mimir/grafana-mimir-values.yaml
- input/grafana/grafana-values.yaml
This PR updates monitoring tools such as grafana, grafana-loki, grafana-mimir based on secrets fetched from 1password.
Highlights:
Before: The tools used fake-cluster-secret-store
After: The tools will fetch secrets from "cf-es-backend" namespace, which are fetched from 1password
> Replace fake css with k8s css for monitoring tools

- input/1password-cluster-secret-store/manifests/ClusterSecretStore_onepass-oci.yaml
This PR changes the value of connectHost of onepass-oci.
Before: http://central-onepass-connect-ociops.external-secrets.svc.cluster.local:8080
After: http://central-onepass-proxy.headscale.svc.cluster.local:8080
> Change the connect host url of the onepass-oci

- input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml
This PR adds scrape_config for getting argocd metrics.
Tested and verified with oci2 cluster and grafana in ociops.
> Update scrape_configs for argocd metrics

- input/grafana-additional-stuff/dashboards/grafana/grafana-argocd-dashboard.yaml
- input/grafana-additional-stuff/dashboards/lgtm-stack/lgtm-argocd-dashboard.yaml
This PR add the configmap of an argocd dashboard at dashboards/grafana and dashboards/lgtm-stack folders. 
Example pic:
> Add argocd dashboard

- input/grafana-loki/grafana-loki-values.yaml
- input/grafana-loki/manifests/sourced/ConfigMap_loki.yaml
- input/grafana-loki/manifests/sourced/Deployment_loki-read.yaml
- input/grafana-loki/manifests/sourced/StatefulSet_loki-backend.yaml
- input/grafana-loki/manifests/sourced/StatefulSet_loki-write.yaml
- input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml
This PR updates otel-log-collector and grafana-loki to add new two labels as filter labels.
Verified with otel-log-collector in oci2 and grafana-loki in ociops.
- Two new labels
- "workload-id": From pod label airm.silogen.ai/workload-id
- "component-id": From pod label airm.silogen.ai/component-id
This is requested by @juhovainio
> Update log collector and grafana loki to add filter labels

- cmd/utils/imageutils.go
- cmd/utils/imageutils_test.go
Modified the image pinning logic to exclude quay.io images from SHA resolution. This change addresses compatibility issues with quay.io's registry API and allows quay.io images to retain their original tags.
Changes:
- Add check in getImageSHA to skip quay.io images
- Update processYAMLFile to handle skipped images gracefully
- Remove unused getQuaySHA function
- Add tests to verify quay.io images are properly skipped
This ensures that while other container images are pinned to their SHA digests for reproducibility, quay.io images will maintain their tag-based references.
> Skip SHA pinning for quay.io images

- input/grafana-additional-stuff/dashboards/grafana/grafana-pvc-dashboard.yaml
- input/grafana-additional-stuff/dashboards/lgtm-stack/lgtm-pvc-dashboard.yaml
This PR adds a pvc dashboard for grafana and lgtm.
> Add a pvc dashboard for grafana and lgtm

- input/otel-lgtm-stack/otel-collectors/collector-manifests.yaml
This PR adds another metric collector to separate scrape jobs for avoiding metric collector crashing due to many scrape jobs at one collector.
There were a couple of events that adding a new scrape led to lose gpu metrics.
Changing parameters of processor of the collector couldn't fix it.
> Add another metric-collector

- input/grafana-additional-stuff/dashboards/grafana/grafana-longhorn-dashboard.yaml
- input/grafana-additional-stuff/dashboards/grafana/grafana-minio-dashboard.yaml
- input/grafana-additional-stuff/dashboards/grafana/grafana-pvc-dashboard.yaml
- input/grafana-additional-stuff/dashboards/lgtm-stack/lgtm-longhorn-dashboard.yaml
- input/grafana-additional-stuff/dashboards/lgtm-stack/lgtm-minio-dashboard.yaml
- input/grafana-additional-stuff/dashboards/lgtm-stack/lgtm-pvc-dashboard.yaml
This PR adds a longhorn dashboard.
The dashboard is from "https://grafana.com/grafana/dashboards/16888-longhorn/" and "k8s_cluster_name" variable added.
> Add longhorn dashboard

- input/otel-lgtm-stack/otel-lgtm/modified-manifests.yaml
This PR adds the Loki port to the LGTM deployment and service.
> Expose Loki to 3100 from LGTM

- input/keycloak-airm-config/keycloak.yaml
Adds a Client Scope "groups" to the AIRM UI Client and sets it to default to include the group membership of its clients in the JWT token.
> SDA-2177 Cluster-Forge changes for KC ClientScope Group

- input/keycloak-config/airm-realm-configmap.yaml
In preparation for access control in kubectl, the groups the user belongs to must be part of the ID token of the user.
Also, use the opportunity to cleanup the organization claim to remove the custom mapper
> Cleanup keycloak realm in preparation for kubectl access control
